/*
 * This source file was generated by the Gradle 'init' task
 */
package com.datcompany;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test
  public void test() {
    assertTrue(true);
  }
}
